export const techStack = {
  eyebrow: "Our Tech Stack",
  headingBefore: "Modern",
  headingEmphasis: "Tech",
  headingAfter: "Stack",
  lead: "Building scalable solutions with cutting-edge tools across web, mobile, AI, and cloud technologies.",
  tools: [
    { name: "JavaScript", icon: "logos:javascript" },
    { name: "Tailwind CSS", icon: "logos:tailwindcss-icon" },
    { name: "HTML5", icon: "logos:html-5" },
    { name: "CSS3", icon: "logos:css-3" },
    { name: "Supabase", icon: "logos:supabase-icon" },
    { name: "PostgreSQL", icon: "logos:postgresql" },
    { name: "Flutter", icon: "logos:flutter" },
    { name: "Dart", icon: "logos:dart" },
    { name: "Node.js", icon: "logos:nodejs-icon" },
    { name: "Python", icon: "logos:python" },
    { name: "Next.js", icon: "logos:nextjs-icon" },
    { name: "React", icon: "logos:react" },
    { name: "TypeScript", icon: "logos:typescript-icon" },
    { name: "Laravel", icon: "logos:laravel" },
    { name: "PHP", icon: "logos:php" },
    { name: "Firebase", icon: "logos:firebase" },
    { name: "Vercel", icon: "logos:vercel-icon" },
    { name: "Stripe", icon: "logos:stripe" },
    { name: "OpenAI", icon: "logos:openai-icon" },
    { name: "Docker", icon: "logos:docker-icon" },
    { name: "Nuxt", icon: "logos:nuxt-icon" },
    { name: "MongoDB", icon: "logos:mongodb-icon" },
    { name: "AWS", icon: "skill-icons:aws-light" },
    { name: "GCP", icon: "logos:google-cloud-icon" },
    { name: "DigitalOcean", icon: "logos:digital-ocean" },
    { name: "WordPress", icon: "logos:wordpress-icon" },
    { name: "Zapier", icon: "logos:zapier-icon" },
    { name: "Postman", icon: "logos:postman-icon" },
    { name: "GitHub", icon: "logos:github-icon" },
    { name: "Git", icon: "logos:git-icon" },
    { name: "VS Code", icon: "logos:visual-studio-code" },
    { name: "Sentry", icon: "logos:sentry-icon" },
    { name: "Redis", icon: "logos:redis" },
    { name: "Expo", icon: "logos:expo-icon" },
    { name: "Prisma", icon: "logos:prisma" },
    { name: "Figma", icon: "logos:figma" },
    { name: "Go", icon: "logos:go" },
    { name: "Rust", icon: "logos:rust" },
    { name: "Kubernetes", icon: "logos:kubernetes" },
    { name: "Terraform", icon: "logos:terraform-icon" },
    { name: "App Store", icon: "logos:apple-app-store" },
    { name: "Google Play", icon: "logos:google-play-icon" },
    { name: "RevenueCat", icon: "simple-icons:revenuecat" },
    { name: "GraphQL", icon: "logos:graphql" },
    { name: "Apollo", icon: "logos:apollostack" },
    { name: "Slack", icon: "logos:slack-icon" },
    { name: "Jira", icon: "logos:jira-icon" },
    { name: "Atlassian", icon: "logos:atlassian" },
    { name: "Notion", icon: "logos:notion-icon" },
    { name: "Jest", icon: "logos:jest" },
    { name: "Cypress", icon: "logos:cypress-icon" },
    { name: "MySQL", icon: "logos:mysql-icon" },
    { name: "Nginx", icon: "logos:nginx" },
    { name: "Linux", icon: "logos:linux-tux" },
    { name: "Ubuntu", icon: "logos:ubuntu" },
    { name: "Framer", icon: "logos:framer" },
    { name: "Vitest", icon: "logos:vitest" },
    { name: "Storybook", icon: "logos:storybook-icon" },
    { name: "Clerk", icon: "simple-icons:clerk" },
    { name: "Upwork", icon: "simple-icons:upwork" },
    { name: "LinkedIn", icon: "logos:linkedin-icon" },
  ],
} as const;
