export const techStack = {
  eyebrow: "Our Tech Stack",
  headingBefore: "Modern",
  headingEmphasis: "Tech",
  headingAfter: "Stack",
  lead: "Building scalable products across web, data, cloud, and automation.",
  groups: [
    {
      label: "Core",
      items: [
        "Laravel",
        "PHP",
        "Node.js",
        "Next.js",
        "React",
        "Vue",
        "Nuxt",
        "TypeScript",
        "Tailwind CSS",
      ],
    },
    {
      label: "Data & Cloud",
      items: ["PostgreSQL", "MySQL", "Redis", "AWS", "Docker", "Nginx", "CI/CD", "Linux"],
    },
    {
      label: "Integrations",
      items: ["REST", "GraphQL", "Stripe", "Zapier", "Twilio", "WordPress"],
    },
    {
      label: "Automation & AI",
      items: ["Python", "OpenAI", "Anthropic (Claude)", "RAG pipelines"],
    },
  ],
  tools: [
    { name: "Laravel", icon: "logos:laravel" },
    { name: "PHP", icon: "logos:php" },
    { name: "Node.js", icon: "logos:nodejs-icon" },
    { name: "Next.js", icon: "logos:nextjs-icon" },
    { name: "React", icon: "logos:react" },
    { name: "Vue", icon: "logos:vue" },
    { name: "Nuxt", icon: "logos:nuxt-icon" },
    { name: "TypeScript", icon: "logos:typescript-icon" },
    { name: "Tailwind CSS", icon: "logos:tailwindcss-icon" },
    { name: "PostgreSQL", icon: "logos:postgresql" },
    { name: "MySQL", icon: "logos:mysql-icon" },
    { name: "Redis", icon: "logos:redis" },
    { name: "AWS", icon: "skill-icons:aws-light" },
    { name: "Docker", icon: "logos:docker-icon" },
    { name: "Nginx", icon: "logos:nginx" },
    { name: "Linux", icon: "logos:linux-tux" },
    { name: "GraphQL", icon: "logos:graphql" },
    { name: "Stripe", icon: "logos:stripe" },
    { name: "Zapier", icon: "logos:zapier-icon" },
    { name: "Twilio", icon: "logos:twilio-icon" },
    { name: "WordPress", icon: "logos:wordpress-icon" },
    { name: "Python", icon: "logos:python" },
    { name: "OpenAI", icon: "logos:openai-icon" },
    { name: "GitHub", icon: "logos:github-icon" },
  ],
} as const;
