/** Phrases the content pipeline must never emit (case-insensitive substring). */
export const BANNED_PHRASES = [
  "game-changer",
  "game changer",
  "revolutioniz",
  "seamless",
  "cutting-edge",
  "unlock the power",
  "supercharge",
  "elevate your",
  "dive into",
  "delve",
  "in today's fast-paced",
  "let that sink in",
  "testament to",
  "boasts",
  "navigate the landscape",
  "at the end of the day",
  "it's worth noting",
  "here's the kicker",
  "buckle up",
  "the truth is",
  "in the realm of",
  "look no further",
  "in the world of",
  "have you ever wondered",
  "thought leader",
  "needle-moving",
  "paradigm shift",
  "best-in-class",
] as const;
